### PR TITLE
Use newer mysql2 gem to fix mysql gem not being loaded error

### PR DESCRIPTION
**Pull request by graudeejs**
Generally this fixes releaf dummy only.

https://stackoverflow.com/questions/22932282/gemloaderror-specified-mysql2-for-database-adapter-but-the-gem-is-not-loade

### CODE REVIEW

**Comment by miks** [comment]
If you remove local Gemfile.lock, effect will be same. That's why we don't lock gems against any specific version to use current versions.

**Comment by graudeejs** [comment]
No, it will not. Install latest rails and try it yourself.
This actually limit mysql2 gem to 0.3.x, while without this patch 0.4.x will be installed.

**Comment by graudeejs** [comment]
The 0.4.0 version of mysql2 was released on 8ht September.

**Comment by kaleemullah360** [comment]
do 
`gem 'mysql2', '~> 0.3.18'` this gem works with `rails version 4.x.x` 
if install `gem 'mysql2', '~> 0.4.0'` it produces gem load error

**Comment by graudeejs** [comment]
@kaleemullah360 I don't think we should limit mysql gem as dependency, since releaf is capable of working with both MySQL and PostgreSQL.

For rails project you will want to set mysql2 anyway and once Rails actually fixes this issue, releaf, will be up and running without modifications.

For now you set ```gem 'mysql2', '~> 0.3.18'``` in your projects Gemfile prior installing releaf

**Pull request merged**
