### PR TITLE
Fix responders error

### PR DESCRIPTION
**Pull request by graudeejs**
Fix error such as this:
```
     NoMethodError:
       undefined method `call' for ActionController::Responder:Class
     # ./releaf-core/app/lib/releaf/responders.rb:5:in `respond_with'
     # ./releaf-core/app/controllers/releaf/base_controller.rb:60:in `edit'
     # ./releaf-content/app/middleware/releaf/content/routes_reloader.rb:10:in `call'
```

### CODE REVIEW

**Comment by miks** [comment]
How can you get this error? By downloading xls?

**Comment by graudeejs** [comment]
Not really
https://travis-ci.org/cubesystems/releaf/jobs/79609131

https://stackoverflow.com/questions/29461524/devise-authentication-error-with-actioncontrollerresponder-and-axlsx-rails-gem

**Comment by miks** [comment]
Fixed by removing zip dependancies.

**Comment by graudeejs** [comment]
Well, that didn't help, because now when you try to ```rake dummy:setup```
you get this: http://pastebin.com/JT5MwVbR
Thats straight from just cloned cubesystems/releaf master branch


You need to lock axlsx_rails to ```'~> 0.3.0'```

https://github.com/graudeejs/releaf/commit/161dc72f3c8dc1c9a504ddbf4f2843ba9b40260e

**Comment by miks** [comment]
Travis don't have this error, also for me locally everything is fine.

**Comment by graudeejs** [comment]
I noticed differences between what gems travis installed and what I had in Gemfile.lock.
So I deleted Gemfile.lock (again), created new rvm gemset, installed latest rails, then run `bundle install`

I still have this problem.

Can you please provide your output of ```gem list```.
Here's mine: http://pastebin.com/9JRQzLDc
Also here's my Gemfile.lock: http://pastebin.com/a59nKSQN

Ruby version: ```ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]```

**Pull request closed without merging**
